# Generated by Django 4.0.2 on 2022-06-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0002_alter_file_timestamp_alter_notification_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='paymentCondition',
            field=models.CharField(default=None, max_length=4096, null=True, verbose_name='Description du mode de paiement'),
        ),
        migrations.AddField(
            model_name='recommandation',
            name='LastWorksiteDate',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Date du dernier chantier'),
        ),
        migrations.AlterField(
            model_name='file',
            name='timestamp',
            field=models.FloatField(default=1656428402.653777, verbose_name='Timestamp de mise à jour'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='timestamp',
            field=models.FloatField(default=1656428402.651546, verbose_name='Timestamp de mise à jour'),
        ),
    ]
