# Generated by Django 4.0.2 on 2022-07-07 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0002_alter_file_timestamp_alter_notification_timestamp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='Role',
        ),
        migrations.RemoveField(
            model_name='company',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='company',
            name='address',
        ),
        migrations.RemoveField(
            model_name='company',
            name='allQualifications',
        ),
        migrations.RemoveField(
            model_name='company',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='company',
            name='capital',
        ),
        migrations.RemoveField(
            model_name='company',
            name='companyMail',
        ),
        migrations.RemoveField(
            model_name='company',
            name='companyPhone',
        ),
        migrations.RemoveField(
            model_name='company',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='company',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='company',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='company',
            name='ntva',
        ),
        migrations.RemoveField(
            model_name='company',
            name='revenue',
        ),
        migrations.RemoveField(
            model_name='company',
            name='saturdayDisponibility',
        ),
        migrations.RemoveField(
            model_name='company',
            name='siret',
        ),
        migrations.RemoveField(
            model_name='company',
            name='size',
        ),
        migrations.RemoveField(
            model_name='company',
            name='starsPME',
        ),
        migrations.RemoveField(
            model_name='company',
            name='starsRecoPME',
        ),
        migrations.RemoveField(
            model_name='company',
            name='starsRecoST',
        ),
        migrations.RemoveField(
            model_name='company',
            name='starsST',
        ),
        migrations.RemoveField(
            model_name='company',
            name='stripeCustomerId',
        ),
        migrations.RemoveField(
            model_name='company',
            name='unity',
        ),
        migrations.RemoveField(
            model_name='company',
            name='webSite',
        ),
        migrations.AlterField(
            model_name='file',
            name='timestamp',
            field=models.FloatField(default=1657190651.845705, verbose_name='Timestamp de mise à jour'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='timestamp',
            field=models.FloatField(default=1657190651.843498, verbose_name='Timestamp de mise à jour'),
        ),
    ]
