# Generated by Django 4.0.2 on 2022-07-04 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0003_alter_file_timestamp_alter_notification_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='stripeCustomerId',
            field=models.CharField(max_length=128, null=True, verbose_name='Customer ID générée par Stripe'),
        ),
        migrations.AlterField(
            model_name='file',
            name='timestamp',
            field=models.FloatField(default=1656924164.724889, verbose_name='Timestamp de mise à jour'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='timestamp',
            field=models.FloatField(default=1656924164.722701, verbose_name='Timestamp de mise à jour'),
        ),
    ]
