# Generated by Django 4.0.2 on 2022-07-07 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0003_remove_company_role_remove_company_activity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='Role',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to='backBatiUni.role'),
        ),
        migrations.AddField(
            model_name='company',
            name='activity',
            field=models.CharField(default='', max_length=256, verbose_name="Activite principale de l'entreprise"),
        ),
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.CharField(default=None, max_length=256, null=True, verbose_name="Adresse de l'entreprise"),
        ),
        migrations.AddField(
            model_name='company',
            name='allQualifications',
            field=models.BooleanField(default=False, verbose_name="Tous corps d'état"),
        ),
        migrations.AddField(
            model_name='company',
            name='amount',
            field=models.FloatField(default=None, null=True, verbose_name='Montant sous-traitant'),
        ),
        migrations.AddField(
            model_name='company',
            name='capital',
            field=models.FloatField(default=None, null=True, verbose_name="Capital de l'entreprise"),
        ),
        migrations.AddField(
            model_name='company',
            name='companyMail',
            field=models.CharField(default=None, max_length=256, null=True, verbose_name='mail de la company'),
        ),
        migrations.AddField(
            model_name='company',
            name='companyPhone',
            field=models.CharField(default=None, max_length=128, null=True, verbose_name='Téléphone du standard'),
        ),
        migrations.AddField(
            model_name='company',
            name='latitude',
            field=models.FloatField(default=None, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.CharField(default=None, max_length=256, null=True, verbose_name="Path du logo de l'entreprise"),
        ),
        migrations.AddField(
            model_name='company',
            name='longitude',
            field=models.FloatField(default=None, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='company',
            name='ntva',
            field=models.CharField(default=None, max_length=32, null=True, unique=True, verbose_name='Numéro de TVA intra communautaire'),
        ),
        migrations.AddField(
            model_name='company',
            name='revenue',
            field=models.FloatField(default=None, null=True, verbose_name="Capital de l'entreprise"),
        ),
        migrations.AddField(
            model_name='company',
            name='saturdayDisponibility',
            field=models.BooleanField(default=False, verbose_name='Disponibilité le Samedi'),
        ),
        migrations.AddField(
            model_name='company',
            name='siret',
            field=models.CharField(default=None, max_length=32, null=True, unique=True, verbose_name='Numéro de Siret'),
        ),
        migrations.AddField(
            model_name='company',
            name='size',
            field=models.IntegerField(default=0.0, verbose_name="Effectif de l'entreprise"),
        ),
        migrations.AddField(
            model_name='company',
            name='starsPME',
            field=models.IntegerField(default=0.0, verbose_name="Notation sous forme d'étoile"),
        ),
        migrations.AddField(
            model_name='company',
            name='starsRecoPME',
            field=models.IntegerField(default=0.0, verbose_name="Notation des recommandations sous forme d'étoile"),
        ),
        migrations.AddField(
            model_name='company',
            name='starsRecoST',
            field=models.IntegerField(default=0.0, verbose_name="Notation des recommandations sous forme d'étoile"),
        ),
        migrations.AddField(
            model_name='company',
            name='starsST',
            field=models.IntegerField(default=0.0, verbose_name="Notation sous forme d'étoile"),
        ),
        migrations.AddField(
            model_name='company',
            name='stripeCustomerId',
            field=models.CharField(max_length=128, null=True, verbose_name='Customer ID générée par Stripe'),
        ),
        migrations.AddField(
            model_name='company',
            name='unity',
            field=models.CharField(default=None, max_length=64, null=True, verbose_name='Unité du montant'),
        ),
        migrations.AddField(
            model_name='company',
            name='webSite',
            field=models.CharField(default=None, max_length=256, null=True, verbose_name='Url du site Web'),
        ),
        migrations.AlterField(
            model_name='file',
            name='timestamp',
            field=models.FloatField(default=1657190690.783879, verbose_name='Timestamp de mise à jour'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='timestamp',
            field=models.FloatField(default=1657190690.781614, verbose_name='Timestamp de mise à jour'),
        ),
    ]
