# Generated by Django 4.0.2 on 2022-06-09 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0003_alter_file_timestamp_alter_notification_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tokenNotification',
            field=models.CharField(blank=True, default='empty token', max_length=512, null=True, verbose_name='Token de validation'),
        ),
        migrations.AlterField(
            model_name='file',
            name='timestamp',
            field=models.FloatField(default=1654768432.371987, verbose_name='Timestamp de mise à jour'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='timestamp',
            field=models.FloatField(default=1654768432.369808, verbose_name='Timestamp de mise à jour'),
        ),
        migrations.AlterField(
            model_name='post',
            name='boostTimestamp',
            field=models.FloatField(default=1654768432.368503, verbose_name='Timestamp de mise à jour'),
        ),
    ]
