# Generated by Django 4.0.2 on 2022-07-29 14:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0004_alter_candidate_date_alter_datepost_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 7, 29, 14, 15, 25, 179903, tzinfo=utc), verbose_name="Date de candidature ou date d'acceptation"),
        ),
        migrations.AlterField(
            model_name='datepost',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 7, 29, 14, 15, 25, 178958, tzinfo=utc), verbose_name='Date du chantier'),
        ),
        migrations.AlterField(
            model_name='file',
            name='timestamp',
            field=models.FloatField(default=1659104125.182098, verbose_name='Timestamp de mise à jour'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='timestamp',
            field=models.FloatField(default=1659104125.179421, verbose_name='Timestamp de mise à jour'),
        ),
        migrations.AlterField(
            model_name='post',
            name='creationDate',
            field=models.DateField(default=datetime.datetime(2022, 7, 29, 14, 15, 25, 177581, tzinfo=utc), verbose_name="Date de creation de l'annonce"),
        ),
    ]
