# Generated by Django 4.0.2 on 2022-07-04 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0004_alter_company_stripecustomerid_alter_file_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='timestamp',
            field=models.FloatField(default=1656924968.862969, verbose_name='Timestamp de mise à jour'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='timestamp',
            field=models.FloatField(default=1656924968.860863, verbose_name='Timestamp de mise à jour'),
        ),
        migrations.AlterField(
            model_name='recommandation',
            name='view',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='viewRecommandation', to='backBatiUni.role', verbose_name='R¨le Sélectionné'),
        ),
    ]
