# Generated by Django 4.0.2 on 2022-06-13 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0005_notification_title_alter_file_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='companyMail',
            field=models.CharField(default=None, max_length=256, null=True, verbose_name='mail de la company'),
        ),
        migrations.AlterField(
            model_name='file',
            name='timestamp',
            field=models.FloatField(default=1655135965.444646, verbose_name='Timestamp de mise à jour'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='timestamp',
            field=models.FloatField(default=1655135965.442504, verbose_name='Timestamp de mise à jour'),
        ),
        migrations.AlterField(
            model_name='post',
            name='boostTimestamp',
            field=models.FloatField(default=0.0, verbose_name='Timestamp de mise à jour'),
        ),
    ]
