# Generated by Django 4.0.2 on 2022-06-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0006_company_companymail_alter_file_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.CharField(default='other', max_length=64, verbose_name='Catégorie de la notification'),
        ),
        migrations.AlterField(
            model_name='file',
            name='timestamp',
            field=models.FloatField(default=1655221801.869007, verbose_name='Timestamp de mise à jour'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='timestamp',
            field=models.FloatField(default=1655221801.866817, verbose_name='Timestamp de mise à jour'),
        ),
    ]
