# Generated by Django 4.0.2 on 2022-06-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0008_alter_file_timestamp_alter_notification_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datepost',
            name='validated',
            field=models.BooleanField(default=True, verbose_name='A été validé'),
        ),
        migrations.AlterField(
            model_name='file',
            name='timestamp',
            field=models.FloatField(default=1656253958.175342, verbose_name='Timestamp de mise à jour'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='timestamp',
            field=models.FloatField(default=1656253958.171684, verbose_name='Timestamp de mise à jour'),
        ),
    ]
