# Generated by Django 4.0.2 on 2022-07-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0009_alter_file_timestamp_alter_notification_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=False, max_length=128, unique=True, verbose_name='Nom du label')),
                ('fileName', models.CharField(default='Unkown', max_length=128, unique=True, verbose_name='Nom du fichier Associé')),
                ('description', models.CharField(default='', max_length=2048, null=True, verbose_name='Description du métier')),
                ('site', models.CharField(default='', max_length=256, null=True, verbose_name='Site internet')),
            ],
            options={
                'verbose_name': 'Label',
            },
        ),
        migrations.AlterField(
            model_name='file',
            name='timestamp',
            field=models.FloatField(default=1657189426.137432, verbose_name='Timestamp de mise à jour'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='timestamp',
            field=models.FloatField(default=1657189426.135226, verbose_name='Timestamp de mise à jour'),
        ),
    ]
