# Generated by Django 4.0.2 on 2022-06-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0009_alter_datepost_validated_alter_file_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='timestamp',
            field=models.FloatField(default=1656254144.443841, verbose_name='Timestamp de mise à jour'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='timestamp',
            field=models.FloatField(default=1656254144.44141, verbose_name='Timestamp de mise à jour'),
        ),
    ]
