# Generated by Django 4.0.2 on 2022-04-11 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0028_candidate_isrefused_alter_candidate_ischoosen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='subContractor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subContractor', to='backBatiUni.mission', verbose_name='Sous Traitant associé'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='unitOfTime',
            field=models.CharField(default='Prix Total', max_length=128, null=True, verbose_name='Unité de temps'),
        ),
        migrations.AlterField(
            model_name='company',
            name='stars',
            field=models.IntegerField(default=0.0, verbose_name="Notation sous forme d'étoile"),
        ),
        migrations.AlterField(
            model_name='file',
            name='timestamp',
            field=models.FloatField(default=1649680071.98663, verbose_name='Timestamp de mise à jour'),
        ),
    ]
