# Generated by Django 4.0.2 on 2022-04-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0029_candidate_subcontractor_alter_candidate_unitoftime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='stars',
            new_name='starsPME',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='subContractor',
        ),
        migrations.AddField(
            model_name='company',
            name='starsST',
            field=models.IntegerField(default=0.0, verbose_name="Notation sous forme d'étoile"),
        ),
        migrations.AlterField(
            model_name='file',
            name='timestamp',
            field=models.FloatField(default=1649684493.401861, verbose_name='Timestamp de mise à jour'),
        ),
    ]
