# Generated by Django 4.0.2 on 2022-04-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0031_post_organisationcommentst_post_organisationst_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datepost',
            options={},
        ),
        migrations.RenameField(
            model_name='datepost',
            old_name='date',
            new_name='timestamp',
        ),
        migrations.AlterUniqueTogether(
            name='datepost',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='datepost',
            name='content',
            field=models.CharField(default='', max_length=128, verbose_name='Contenu du Post'),
        ),
        migrations.AlterField(
            model_name='file',
            name='timestamp',
            field=models.FloatField(default=1649856937.701733, verbose_name='Timestamp de mise à jour'),
        ),
    ]
