# Generated by Django 4.0.2 on 2022-04-13 13:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0032_alter_datepost_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datepost',
            options={'verbose_name': 'DatePost'},
        ),
        migrations.RenameField(
            model_name='datepost',
            old_name='timestamp',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='file',
            name='timestamp',
            field=models.FloatField(default=1649857843.290287, verbose_name='Timestamp de mise à jour'),
        ),
        migrations.AlterUniqueTogether(
            name='datepost',
            unique_together={('Post', 'Mission', 'date')},
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateField(default=django.utils.timezone.now, verbose_name='Date du chantier')),
                ('content', models.CharField(default='', max_length=128, verbose_name='Contenu du Post')),
                ('Mission', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MissionNotification', to='backBatiUni.mission', verbose_name='Mission associée')),
                ('Post', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PostNotification', to='backBatiUni.post', verbose_name='Annonce associée')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='datepost',
            name='content',
        ),
    ]
