# Generated by Django 4.0.2 on 2022-04-13 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0033_alter_datepost_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='Company',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='CompanyNotification', to='backBatiUni.company', verbose_name='Société associé'),
        ),
        migrations.AddField(
            model_name='notification',
            name='Role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='backBatiUni.role'),
        ),
        migrations.AddField(
            model_name='notification',
            name='hasBeenViewed',
            field=models.BooleanField(default=False, verbose_name='A été vu'),
        ),
        migrations.AlterField(
            model_name='file',
            name='timestamp',
            field=models.FloatField(default=1649861359.694992, verbose_name='Timestamp de mise à jour'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='Mission',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='MissionNotification', to='backBatiUni.mission', verbose_name='Mission associée'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='Post',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='PostNotification', to='backBatiUni.post', verbose_name='Annonce associée'),
        ),
        migrations.AlterField(
            model_name='post',
            name='subContractorName',
            field=models.CharField(default=None, max_length=128, null=True, verbose_name='Nom du sous traitant'),
        ),
    ]
