# Generated by Django 4.0.2 on 2022-04-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0035_alter_file_timestamp_alter_notification_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='timestamp',
            field=models.FloatField(default=1649867938.96901, verbose_name='Timestamp de mise à jour'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='Role',
            field=models.CharField(default='PME', max_length=64, verbose_name='Rôle effectif durant la notation'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='timestamp',
            field=models.FloatField(default=1649867938.967232, verbose_name='Timestamp de mise à jour'),
        ),
    ]
