# Generated by Django 4.0.2 on 2022-04-18 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0036_alter_file_timestamp_alter_notification_role_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'Notification'},
        ),
        migrations.AddField(
            model_name='candidate',
            name='isViewed',
            field=models.BooleanField(default=False, null=True, verbose_name='Candidature vue'),
        ),
        migrations.AlterField(
            model_name='file',
            name='timestamp',
            field=models.FloatField(default=1650302589.844076, verbose_name='Timestamp de mise à jour'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='timestamp',
            field=models.FloatField(default=1650302589.842286, verbose_name='Timestamp de mise à jour'),
        ),
    ]
