# Generated by Django 4.0.2 on 2022-04-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0037_alter_notification_options_candidate_isviewed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='nature',
            field=models.CharField(default='other', max_length=64, verbose_name='Nature de la notification'),
        ),
        migrations.AlterField(
            model_name='file',
            name='timestamp',
            field=models.FloatField(default=1650633292.475252, verbose_name='Timestamp de mise à jour'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='timestamp',
            field=models.FloatField(default=1650633292.473375, verbose_name='Timestamp de mise à jour'),
        ),
    ]
