# Generated by Django 4.0.2 on 2022-04-22 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0038_notification_nature_alter_file_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='subContractor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SubContractorAuthor', to='backBatiUni.company', verbose_name='Société destinatrice'),
        ),
        migrations.AlterField(
            model_name='file',
            name='timestamp',
            field=models.FloatField(default=1650648285.344036, verbose_name='Timestamp de mise à jour'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='Company',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='CompanyNotification', to='backBatiUni.company', verbose_name='Sous traitant associé'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='timestamp',
            field=models.FloatField(default=1650648285.342105, verbose_name='Timestamp de mise à jour'),
        ),
    ]
