# Generated by Django 4.0.2 on 2022-04-28 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0039_notification_subcontractor_alter_file_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='timestamp',
            field=models.FloatField(default=1651155196.590897, verbose_name='Timestamp de mise à jour'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='timestamp',
            field=models.FloatField(default=1651155196.588728, verbose_name='Timestamp de mise à jour'),
        ),
        migrations.CreateModel(
            name='InviteFriend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailTarget', models.CharField(default='', max_length=256, verbose_name='email du destinataire')),
                ('invitationAuthor', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='backBatiUni.userprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
