# Generated by Django 4.0.2 on 2022-04-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0040_alter_file_timestamp_alter_notification_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitefriend',
            options={'verbose_name': 'InviteFriend'},
        ),
        migrations.AddField(
            model_name='invitefriend',
            name='token',
            field=models.CharField(default='', max_length=64, verbose_name='token'),
        ),
        migrations.AddField(
            model_name='invitefriend',
            name='used',
            field=models.BooleanField(default=False, verbose_name='A été utilisé'),
        ),
        migrations.AddField(
            model_name='post',
            name='hourlyEndChange',
            field=models.CharField(default=None, max_length=128, null=True, verbose_name='Horaire de fin de chantier'),
        ),
        migrations.AddField(
            model_name='post',
            name='hourlyStartChange',
            field=models.CharField(default=None, max_length=128, null=True, verbose_name='Horaire de début de chantier'),
        ),
        migrations.AlterField(
            model_name='file',
            name='timestamp',
            field=models.FloatField(default=1651225359.803779, verbose_name='Timestamp de mise à jour'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='timestamp',
            field=models.FloatField(default=1651225359.801644, verbose_name='Timestamp de mise à jour'),
        ),
    ]
