# Generated by Django 4.0.2 on 2022-04-29 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0041_alter_invitefriend_options_invitefriend_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='timestamp',
            field=models.FloatField(default=1651225589.502984, verbose_name='Timestamp de mise à jour'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='content',
            field=models.CharField(default='', max_length=1024, verbose_name='Contenu du Post'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='timestamp',
            field=models.FloatField(default=1651225589.50077, verbose_name='Timestamp de mise à jour'),
        ),
        migrations.AlterField(
            model_name='post',
            name='hourlyEndChange',
            field=models.CharField(default=None, max_length=128, null=True, verbose_name='Horaire de fin de chantier proposé en modificatio'),
        ),
        migrations.AlterField(
            model_name='post',
            name='hourlyStartChange',
            field=models.CharField(default=None, max_length=128, null=True, verbose_name='Horaire de début de chantier proposé en modification'),
        ),
    ]
