# Generated by Django 4.0.2 on 2022-04-29 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0042_alter_file_timestamp_alter_notification_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datepost',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='A été effacé'),
        ),
        migrations.AddField(
            model_name='datepost',
            name='validated',
            field=models.BooleanField(default=True, verbose_name='A été effacé'),
        ),
        migrations.AlterField(
            model_name='file',
            name='timestamp',
            field=models.FloatField(default=1651226512.152616, verbose_name='Timestamp de mise à jour'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='timestamp',
            field=models.FloatField(default=1651226512.15049, verbose_name='Timestamp de mise à jour'),
        ),
    ]
