# Generated by Django 4.0.2 on 2022-05-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0044_remove_invitefriend_used_invitefriend_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tokenFriend',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name="Token pour invitation d'ami"),
        ),
        migrations.AlterField(
            model_name='file',
            name='timestamp',
            field=models.FloatField(default=1652190762.415245, verbose_name='Timestamp de mise à jour'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='timestamp',
            field=models.FloatField(default=1652190762.413083, verbose_name='Timestamp de mise à jour'),
        ),
        migrations.AlterUniqueTogether(
            name='detailedpost',
            unique_together={('Post', 'Mission', 'date')},
        ),
    ]
