# Generated by Django 4.0.2 on 2022-05-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0048_alter_file_timestamp_alter_notification_timestamp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='isBoosted',
        ),
        migrations.AlterField(
            model_name='file',
            name='timestamp',
            field=models.FloatField(default=1652452616.747254, verbose_name='Timestamp de mise à jour'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='timestamp',
            field=models.FloatField(default=1652452616.745146, verbose_name='Timestamp de mise à jour'),
        ),
        migrations.AlterField(
            model_name='post',
            name='boostTimestamp',
            field=models.FloatField(default=1652452616.743826, verbose_name='Timestamp de mise à jour'),
        ),
    ]
