# Generated by Django 4.0.2 on 2022-05-18 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0049_remove_post_isboosted_alter_file_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='capital',
            field=models.FloatField(default=None, null=True, verbose_name="Capital de l'entreprise"),
        ),
        migrations.AlterField(
            model_name='file',
            name='timestamp',
            field=models.FloatField(default=1652886420.769843, verbose_name='Timestamp de mise à jour'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='timestamp',
            field=models.FloatField(default=1652886420.767793, verbose_name='Timestamp de mise à jour'),
        ),
        migrations.AlterField(
            model_name='post',
            name='boostTimestamp',
            field=models.FloatField(default=1652886420.766585, verbose_name='Timestamp de mise à jour'),
        ),
    ]
