# Generated by Django 4.0.2 on 2022-05-22 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0052_alter_company_address_alter_file_timestamp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervision',
            name='SupervisionAssociated',
        ),
        migrations.AlterField(
            model_name='file',
            name='timestamp',
            field=models.FloatField(default=1653223905.572281, verbose_name='Timestamp de mise à jour'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='timestamp',
            field=models.FloatField(default=1653223905.570154, verbose_name='Timestamp de mise à jour'),
        ),
        migrations.AlterField(
            model_name='post',
            name='boostTimestamp',
            field=models.FloatField(default=1653223905.568889, verbose_name='Timestamp de mise à jour'),
        ),
    ]
