# Generated by Django 4.0.2 on 2022-05-25 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0056_remove_supervision_mission_supervision_datepost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervision',
            name='Mission',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='backBatiUni.mission', verbose_name='Mission associée'),
        ),
        migrations.AlterField(
            model_name='file',
            name='timestamp',
            field=models.FloatField(default=1653496125.459873, verbose_name='Timestamp de mise à jour'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='timestamp',
            field=models.FloatField(default=1653496125.457645, verbose_name='Timestamp de mise à jour'),
        ),
        migrations.AlterField(
            model_name='post',
            name='boostTimestamp',
            field=models.FloatField(default=1653496125.456327, verbose_name='Timestamp de mise à jour'),
        ),
    ]
