# Generated by Django 4.0.2 on 2022-05-29 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0058_alter_detailedpost_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervision',
            name='Mission',
        ),
        migrations.AlterField(
            model_name='file',
            name='timestamp',
            field=models.FloatField(default=1653839844.328858, verbose_name='Timestamp de mise à jour'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='timestamp',
            field=models.FloatField(default=1653839844.326685, verbose_name='Timestamp de mise à jour'),
        ),
        migrations.AlterField(
            model_name='post',
            name='boostTimestamp',
            field=models.FloatField(default=1653839844.325398, verbose_name='Timestamp de mise à jour'),
        ),
    ]
