# Generated by Django 4.0.2 on 2022-05-31 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0059_remove_supervision_mission_alter_file_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='timestamp',
            field=models.FloatField(default=1654012464.021674, verbose_name='Timestamp de mise à jour'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='timestamp',
            field=models.FloatField(default=1654012464.019479, verbose_name='Timestamp de mise à jour'),
        ),
        migrations.AlterField(
            model_name='post',
            name='boostTimestamp',
            field=models.FloatField(default=1654012464.018162, verbose_name='Timestamp de mise à jour'),
        ),
        migrations.CreateModel(
            name='BlockedCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False, verbose_name='Status du bloqué')),
                ('date', models.DateField(default=None, null=True, verbose_name="Date de l'inscription")),
                ('blocked', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='blocked', to='backBatiUni.company', verbose_name='Company who is blocked')),
                ('blocker', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='blocking', to='backBatiUni.company', verbose_name='Company who is blocking')),
            ],
            options={
                'verbose_name': 'BlockedCandidate',
                'unique_together': {('blocker', 'blocked')},
            },
        ),
    ]
